cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true
blockExoticSubdeps: true
onlyBuiltDependencies:
  - core-js-pure
  - cypress
  - esbuild
  - sharp
  - unrs-resolver

packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  core-js-pure: true
  cypress: true
  esbuild: true
  sharp: true
  unrs-resolver: true
